version: '3'

services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./auction_system:/usr/src/app
    environment:
      - POSTGRES_DB=SukuleloDatabase
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Dockerproject1
      - POSTGRES_HOST=db
    networks:
      - mitchellnetwork

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: SukuleloDatabase
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Dockerproject1
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mitchellnetwork

volumes:
  postgres_data:

networks:
  mitchellnetwork:
