version: '3'

services:
  web:
    build: .
    image: mitchellimage
    ports:
      - "8000:8000"
    volumes:
      - ./auction_system:/usr/src/app
    depends_on:
      - postgres

  postgres:
    image: postgres
    command: /bin/sh -c "while true; do echo Hello from Mitchell  Container; sleep 1500; done"

