version: '3'

services:
  web:
    build: 
      context: .
    image: "mitchell"
    ports:
      - "8000:8000"
    volumes:
      - ./auction_system:/usr/src/app
    depends_on:
      - db

  db:
    image: "sqlite-container"
    ports:
      - "5432:5432" 
    volumes:
      - ./auction_system/db.sqlite3:/usr/src/app/db.sqlite3




         


