# Use an official SQLite image as the base image
FROM sqlite-container

# Set the working directory inside the container
WORKDIR /usr/src/app

# Copy the SQLite database file into the container
COPY db.sqlite3 /usr/src/app/

# Specify the command to run when the container starts
CMD ["sqlite3", "db.sqlite3"]
