# Generated by Django 3.2 on 2023-05-19 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0003_auto_20230519_1455'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='date_paid',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='payment_METHOD',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='payment_status',
        ),
        migrations.AddField(
            model_name='payment',
            name='acc_number',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('PAYPAL', 'PAYPAL'), ('VISA CARD', 'VISA CARD'), ('MASTERCARD', 'MASTERCARD')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='bid',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='auction.bid'),
        ),
    ]
